services:
  campaignmodule:
    container_name: 'campaignmodule-app'
    image: 'campaignmodule'
    build:
      context: .
      dockerfile: src/CampaignModule.Api/Dockerfile
    ports:
      - "5002:80"
    depends_on:
      - 'postgres'
    environment:
      DbConnString: "host=postgres;Port=5432;Database=postgres;User Id=dbuser;Password=1q2w3e;"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:80"
    networks:
      - campaignmodule-network
        
  
  postgres:
    ports:
      - '5432:5432'
    container_name: 'campaignmodule-postgresql'
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=1q2w3e
      - POSTGRES_DB=postgres
    image: 'postgres'
    networks:
      - campaignmodule-network
  
volumes:
  db_volume:

networks:
  campaignmodule-network:
    driver: bridge